# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-21 18:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nacionalidad', models.CharField(max_length=40)),
                ('procedencia', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Huesped',
                'verbose_name_plural': 'Huespedes',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=70)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nac', models.DateField(verbose_name=b'Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[(b'masculino', b'Masculino'), (b'femenino', b'Femenino')], default=b'masculino', max_length=10)),
                ('telefono', models.CharField(max_length=13)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=150)),
                ('estado', models.BooleanField(default=True)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Persona')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personales',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Rol'),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='huesped',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Persona'),
        ),
    ]
