# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 17:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellidos', models.CharField(max_length=70)),
                ('dni', models.CharField(max_length=8)),
                ('fecha_nac', models.DateTimeField(verbose_name=b'Fecha de Nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=255, verbose_name=b'G\xc3\xa9nero')),
                ('telefono', models.CharField(max_length=13)),
                ('nacionalidad', models.CharField(max_length=40)),
                ('procedencia', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('sexo', models.CharField(blank=True, choices=[(b'M', b'Masculino'), (b'F', b'Femenino')], max_length=255, verbose_name=b'G\xc3\xa9nero')),
                ('direccion', models.CharField(max_length=150)),
                ('telefono', models.CharField(max_length=13)),
                ('imagen', models.ImageField(upload_to=b'perfiles')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='personal',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Rol'),
        ),
        migrations.AddField(
            model_name='personal',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
