# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('perfiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=5, unique=True)),
                ('tipo', models.CharField(blank=True, choices=[(b'mds', b'mds'), (b'mdt', b'mdt'), (b'mdd', b'mdd')], max_length=5, verbose_name=b'Tipo')),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ingreso', models.DateTimeField()),
                ('fec_salida', models.DateTimeField()),
                ('tarifa', models.CharField(max_length=6)),
                ('forma_pago', models.CharField(max_length=6)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.Habitacion')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfiles.Huesped')),
            ],
        ),
    ]
