# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-08 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[(b'swb', b'Habitaci\xc3\xb3n Simple/Matrimonial'), (b'dwb', b'Habitaci\xc3\xb3n doble'), (b'mat', b'Habitaci\xc3\xb3n triple/departamento')], max_length=5, verbose_name=b'Tipo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='forma_pago',
            field=models.CharField(choices=[(b'Efectivo', b'Efectivo'), (b'Tarjeta', b'Tarjeta')], max_length=10),
        ),
    ]
