# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-13 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20160108_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='estado',
            field=models.CharField(blank=True, choices=[(b'libre', b'Libre'), (b'reservado', b'Reservado'), (b'ocupado', b'Ocupado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[(b'swb', b'Habitaci\xc3\xb3n Simple'), (b'dwb', b'Habitaci\xc3\xb3n doble'), (b'mat', b'Habitaci\xc3\xb3n triple/departamento')], max_length=5, verbose_name=b'Tipo'),
        ),
        migrations.AlterField(
            model_name='registro',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[(b'efectivo', b'Efectivo'), (b'tarjeta', b'Tarjeta')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registro',
            name='tarifa',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
